### ISSUE TITLE
Yosys uhdm frontend fails on parsing 2D arrays in module IOs

### ISSUE THREAD

**Issue by kamilrakoczy** [alainmarcel/uhdm-integration#49] opened 2020-10-30 10:07 UTC
Yosys uhdm frontend fails on parsing 2D arrays in module IOs. It is creating AST node, that can't by simplified to AST_CONSTANT. It makes yosys to fail on detecting width with message:
```
Unsupported expression on dynamic range select on signal
```

**Comment by kbieganski** [comment] 2020-11-03 15:55
This error is caused by Yosys not finding necessary information about wires, because the module is incomplete (it's a parametrized module that's unused, so Surelog doesn't fully populate it). We should detect these incomplete modules and remove them from the design.

**Comment by kbieganski** [comment] 2020-11-03 16:07
Should be fixed by https://github.com/antmicro/yosys/commit/1b3be994f2efadf5222d93638608574ab190cdcf

**Comment by kbieganski** [comment] 2020-11-06 08:00
Merged by @kamilrakoczy

**Closed by kbieganski** 2020-11-06 08:00 UTC
